-- MySQL Script generated by MySQL Workbench
-- Wed May 17 22:43:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AccessControl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AccessControl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AccessControl` DEFAULT CHARACTER SET utf8 ;
USE `AccessControl` ;

-- -----------------------------------------------------
-- Table `AccessControl`.`Calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessControl`.`Calendario` ;

CREATE TABLE IF NOT EXISTS `AccessControl`.`Calendario` (
  `id_calendario` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`id_calendario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccessControl`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessControl`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `AccessControl`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(225) NULL,
  `password` VARCHAR(225) NULL,
  `tipo_usuario` SMALLINT(5) NULL,
  `Calendario_id_calendario` BIGINT(19) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuario_Calendario_idx` (`Calendario_id_calendario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Calendario`
    FOREIGN KEY (`Calendario_id_calendario`)
    REFERENCES `AccessControl`.`Calendario` (`id_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccessControl`.`Semana`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessControl`.`Semana` ;

CREATE TABLE IF NOT EXISTS `AccessControl`.`Semana` (
  `id_Semana` BIGINT(19) NOT NULL,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`id_Semana`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccessControl`.`Calendario_Semanas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessControl`.`Calendario_Semanas` ;

CREATE TABLE IF NOT EXISTS `AccessControl`.`Calendario_Semanas` (
  `Calendario_id_calendario` BIGINT(19) NOT NULL,
  `Semana_id_Semana` BIGINT(19) NOT NULL,
  `fechaInicio` DATE NULL,
  PRIMARY KEY (`Calendario_id_calendario`, `Semana_id_Semana`),
  INDEX `fk_Calendario_has_Semana_Calendario1_idx` (`Calendario_id_calendario` ASC) VISIBLE,
  INDEX `fk_Calendario_has_Semana_Semana1_idx` (`Semana_id_Semana` ASC) VISIBLE,
  CONSTRAINT `fk_Calendario_has_Semana_Calendario1`
    FOREIGN KEY (`Calendario_id_calendario`)
    REFERENCES `AccessControl`.`Calendario` (`id_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendario_has_Semana_Semana1`
    FOREIGN KEY (`Semana_id_Semana`)
    REFERENCES `AccessControl`.`Semana` (`id_Semana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccessControl`.`Hora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessControl`.`Hora` ;

CREATE TABLE IF NOT EXISTS `AccessControl`.`Hora` (
  `id_hora` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `inicio` TIME NULL,
  `fin` TIME NULL,
  `Semana_id_Semana` BIGINT(19) NOT NULL,
  `dia` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_hora`),
  INDEX `fk_Hora_Semana1_idx` (`Semana_id_Semana` ASC) VISIBLE,
  UNIQUE INDEX `id_hora_UNIQUE` (`id_hora` ASC) VISIBLE,
  CONSTRAINT `fk_Hora_Semana1`
    FOREIGN KEY (`Semana_id_Semana`)
    REFERENCES `AccessControl`.`Semana` (`id_Semana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccessControl`.`Puerta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessControl`.`Puerta` ;

CREATE TABLE IF NOT EXISTS `AccessControl`.`Puerta` (
  `id_Puerta` BIGINT(19) NOT NULL,
  `id_zona` BIGINT(19) NOT NULL,
  PRIMARY KEY (`id_Puerta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccessControl`.`Horas_Puertas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessControl`.`Horas_Puertas` ;

CREATE TABLE IF NOT EXISTS `AccessControl`.`Horas_Puertas` (
  `Hora_id_hora` BIGINT(19) NOT NULL,
  `Puerta_id_Puerta` BIGINT(19) NOT NULL,
  PRIMARY KEY (`Hora_id_hora`, `Puerta_id_Puerta`),
  INDEX `fk_Hora_has_Puerta_Puerta1_idx` (`Puerta_id_Puerta` ASC) VISIBLE,
  INDEX `fk_Hora_has_Puerta_Hora1_idx` (`Hora_id_hora` ASC) VISIBLE,
  CONSTRAINT `fk_Hora_has_Puerta_Hora1`
    FOREIGN KEY (`Hora_id_hora`)
    REFERENCES `AccessControl`.`Hora` (`id_hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hora_has_Puerta_Puerta1`
    FOREIGN KEY (`Puerta_id_Puerta`)
    REFERENCES `AccessControl`.`Puerta` (`id_Puerta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccessControl`.`Zona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessControl`.`Zona` ;

CREATE TABLE IF NOT EXISTS `AccessControl`.`Zona` (
  `id_zona` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_zona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccessControl`.`Zonas_Puertas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessControl`.`Zonas_Puertas` ;

CREATE TABLE IF NOT EXISTS `AccessControl`.`Zonas_Puertas` (
  `Zona_id_zona` BIGINT(19) NOT NULL,
  `Puerta_id_Puerta` BIGINT(19) NOT NULL,
  PRIMARY KEY (`Zona_id_zona`, `Puerta_id_Puerta`),
  INDEX `fk_Zona_has_Puerta_Puerta1_idx` (`Puerta_id_Puerta` ASC) VISIBLE,
  INDEX `fk_Zona_has_Puerta_Zona1_idx` (`Zona_id_zona` ASC) VISIBLE,
  CONSTRAINT `fk_Zona_has_Puerta_Zona1`
    FOREIGN KEY (`Zona_id_zona`)
    REFERENCES `AccessControl`.`Zona` (`id_zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zona_has_Puerta_Puerta1`
    FOREIGN KEY (`Puerta_id_Puerta`)
    REFERENCES `AccessControl`.`Puerta` (`id_Puerta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
