-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 08:20:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AccesControl Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AccesControl Database
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `AccesControl Database` DEFAULT CHARACTER SET utf8 ;
-- USE `AccesControl Database` ;

-- -----------------------------------------------------
-- Table `Puerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Puerta` (
  `idPuerta` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  `Observaciones` VARCHAR(255) NULL,
  `GrupoPuerta_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idPuerta`),
  UNIQUE INDEX `idPuerta_UNIQUE` (`idPuerta` ASC) VISIBLE,
  INDEX `fk_grupoPuerta` (`GrupoPuerta_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_grupopuerta`
	FOREIGN KEY (`GrupoPuerta_idGrupo`)
    REFERENCES `GrupoPuerta`(`idGrupoPuerta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GrupoPuerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoPuerta` (
  `idGrupoPuerta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idGrupoPuerta`),
  UNIQUE INDEX `idGrupoPuerta_UNIQUE` (`idGrupoPuerta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GrupoPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GrupoPersona` (
  `idGrupoPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idGrupoPersona`),
  UNIQUE INDEX `idGrupoPersona_UNIQUE` (`idGrupoPersona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Periodo` (
  `idPeriodo` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  `Ano` INT NULL,
  PRIMARY KEY (`idPeriodo`),
  UNIQUE INDEX `idPeriodo_UNIQUE` (`idPeriodo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccesosSemana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AccesosSemana` (
  `idAccesosSemana` BIGINT NOT NULL AUTO_INCREMENT,
  `DiaSemana` VARCHAR(45) NOT NULL,
  `HoraInciol` DATETIME NULL,
  `HoraFin` DATETIME NOT NULL,
  `GrupoPuerta_idGrupoPuerta` INT NOT NULL,
  `GrupoPersona_idGrupoPersona` INT NOT NULL,
  `Periodo_idPeriodo` INT NOT NULL,
  PRIMARY KEY (`idAccesosSemana`),
  UNIQUE INDEX `idAccesosSemana_UNIQUE` (`idAccesosSemana` ASC) VISIBLE,
  INDEX `fk_AccesosSemana_GrupoPuerta1_idx` (`GrupoPuerta_idGrupoPuerta` ASC) VISIBLE,
  INDEX `fk_AccesosSemana_GrupoPersona1_idx` (`GrupoPersona_idGrupoPersona` ASC) VISIBLE,
  INDEX `fk_AccesosSemana_Periodo1_idx` (`Periodo_idPeriodo` ASC) VISIBLE,
  CONSTRAINT `fk_AccesosSemana_GrupoPuerta1`
    FOREIGN KEY (`GrupoPuerta_idGrupoPuerta`)
    REFERENCES `GrupoPuerta` (`idGrupoPuerta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AccesosSemana_GrupoPersona1`
    FOREIGN KEY (`GrupoPersona_idGrupoPersona`)
    REFERENCES `GrupoPersona` (`idGrupoPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AccesosSemana_Periodo1`
    FOREIGN KEY (`Periodo_idPeriodo`)
    REFERENCES `Periodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `SemanaTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SemanaTipo` (
  `idSemanaTipo` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  `DiaSemana` VARCHAR(45) NULL,
  `HoraInicio` DATETIME NULL,
  `HoraFin` DATETIME NULL,
  `GrupoPuerta_idGrupoPuerta` INT NOT NULL,
  `GrupoPersona_idGrupoPersona` INT NOT NULL,
  PRIMARY KEY (`idSemanaTipo`),
  UNIQUE INDEX `idSemanaTipo_UNIQUE` (`idSemanaTipo` ASC) VISIBLE,
  INDEX `fk_SemanaTipo_GrupoPuerta1_idx` (`GrupoPuerta_idGrupoPuerta` ASC) VISIBLE,
  INDEX `fk_SemanaTipo_GrupoPersona1_idx` (`GrupoPersona_idGrupoPersona` ASC) VISIBLE,
  CONSTRAINT `fk_SemanaTipo_GrupoPuerta1`
    FOREIGN KEY (`GrupoPuerta_idGrupoPuerta`)
    REFERENCES `GrupoPuerta` (`idGrupoPuerta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SemanaTipo_GrupoPersona1`
    FOREIGN KEY (`GrupoPersona_idGrupoPersona`)
    REFERENCES `GrupoPersona` (`idGrupoPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(255) NULL,
  `Apellidos` VARCHAR(255) NULL,
  `Celular` VARCHAR(20) NULL,
  `Correo` VARCHAR(45) NULL,
  `Clave` VARCHAR(255) NULL,
  `UID` VARCHAR(255) NULL,
  `Imagen` LONGBLOB NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DetalleGrupoPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DetalleGrupoPersona` (
  `idDetalleGrupoPersona` INT NOT NULL AUTO_INCREMENT,
  `Persona_idPersona` INT NOT NULL,
  `GrupoPersona_idGrupoPersona` INT NOT NULL,
  PRIMARY KEY (`idDetalleGrupoPersona`),
  INDEX `fk_DetalleGrupoPersona_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  INDEX `fk_DetalleGrupoPersona_GrupoPersona1_idx` (`GrupoPersona_idGrupoPersona` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleGrupoPersona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleGrupoPersona_GrupoPersona1`
    FOREIGN KEY (`GrupoPersona_idGrupoPersona`)
    REFERENCES `GrupoPersona` (`idGrupoPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
