-- MySQL Script generated by MySQL Workbench
-- Tue Jun 13 21:10:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema accesscontrol
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `accesscontrol` DEFAULT CHARACTER SET utf8mb3 ; --
-- USE `accesscontrol` ; --

-- -----------------------------------------------------
-- Table `grupopersona`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `grupopersona` (
  `idGrupoPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupoPersona`),
  UNIQUE INDEX `idGrupoPersona_UNIQUE` (`idGrupoPersona` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `grupopuerta`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `grupopuerta` (
  `idGrupoPuerta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupoPuerta`),
  UNIQUE INDEX `idGrupoPuerta_UNIQUE` (`idGrupoPuerta` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `semanatipo`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `accesscontrol`.`semanatipo` (
  `idSemanaTipo` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idSemanaTipo`),
  UNIQUE INDEX `idSemanaTipo_UNIQUE` (`idSemanaTipo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2224
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `accesossemana`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `accesossemana` (
  `idAccesosSemana` BIGINT NOT NULL AUTO_INCREMENT,
  `DiaSemana` VARCHAR(45) NOT NULL,
  `HoraInciol` INT NULL DEFAULT NULL,
  `GrupoPuerta_idGrupoPuerta` INT NOT NULL,
  `GrupoPersona_idGrupoPersona` INT NOT NULL,
  `SemanaTipo_idSemanaTipo` INT NOT NULL,
  PRIMARY KEY (`idAccesosSemana`),
  UNIQUE INDEX `idAccesosSemana_UNIQUE` (`idAccesosSemana` ASC) VISIBLE,
  INDEX `fk_AccesosSemana_GrupoPuerta1_idx` (`GrupoPuerta_idGrupoPuerta` ASC) VISIBLE,
  INDEX `fk_AccesosSemana_GrupoPersona1_idx` (`GrupoPersona_idGrupoPersona` ASC) VISIBLE,
  INDEX `fk_AccesosSemana_SemanaTipo1_idx` (`SemanaTipo_idSemanaTipo` ASC) VISIBLE,
  CONSTRAINT `fk_AccesosSemana_GrupoPersona1`
    FOREIGN KEY (`GrupoPersona_idGrupoPersona`)
    REFERENCES `grupopersona` (`idGrupoPersona`),
  CONSTRAINT `fk_AccesosSemana_GrupoPuerta1`
    FOREIGN KEY (`GrupoPuerta_idGrupoPuerta`)
    REFERENCES `grupopuerta` (`idGrupoPuerta`),
  CONSTRAINT `fk_AccesosSemana_SemanaTipo1`
    FOREIGN KEY (`SemanaTipo_idSemanaTipo`)
    REFERENCES `semanatipo` (`idSemanaTipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `persona`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(255) NULL DEFAULT NULL,
  `Apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `Celular` VARCHAR(20) NULL DEFAULT NULL,
  `Correo` VARCHAR(45) NULL DEFAULT NULL,
  `Clave` VARCHAR(255) NULL DEFAULT NULL,
  `UID` VARCHAR(255) NULL DEFAULT NULL,
  `Imagen` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `detallegrupopersona`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `detallegrupopersona` (
  `idDetalleGrupoPersona` INT NOT NULL AUTO_INCREMENT,
  `Persona_idPersona` INT NOT NULL,
  `GrupoPersona_idGrupoPersona` INT NOT NULL,
  PRIMARY KEY (`idDetalleGrupoPersona`),
  INDEX `fk_DetalleGrupoPersona_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  INDEX `fk_DetalleGrupoPersona_GrupoPersona1_idx` (`GrupoPersona_idGrupoPersona` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleGrupoPersona_GrupoPersona1`
    FOREIGN KEY (`GrupoPersona_idGrupoPersona`)
    REFERENCES `grupopersona` (`idGrupoPersona`),
  CONSTRAINT `fk_DetalleGrupoPersona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `persona` (`idPersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `puerta`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `puerta` (
  `idPuerta` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `Ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  `Observaciones` VARCHAR(255) NULL DEFAULT NULL,
  `GrupoPuerta_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idPuerta`),
  UNIQUE INDEX `idPuerta_UNIQUE` (`idPuerta` ASC) VISIBLE,
  INDEX `fk_grupoPuerta` (`GrupoPuerta_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_grupopuerta`
    FOREIGN KEY (`GrupoPuerta_idGrupo`)
    REFERENCES `grupopuerta` (`idGrupoPuerta`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agenda`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `agenda` (
  `idagenda` INT NOT NULL AUTO_INCREMENT,
  `FechaInicio` DATE NOT NULL,
  `semanatipo_idSemanaTipo` INT NOT NULL,
  PRIMARY KEY (`idagenda`, `semanatipo_idSemanaTipo`),
  UNIQUE INDEX `idagenda_UNIQUE` (`idagenda` ASC) VISIBLE,
  INDEX `fk_agenda_semanatipo1_idx` (`semanatipo_idSemanaTipo` ASC) VISIBLE,
  CONSTRAINT `fk_agenda_semanatipo1`
    FOREIGN KEY (`semanatipo_idSemanaTipo`)
    REFERENCES `accesscontrol`.`semanatipo` (`idSemanaTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
